### ISSUE TITLE
DevOps: Set up DEV environment

### ISSUE THREAD

**Issue by amyburness** [kartoza/africa_rangeland_watch#25]
### Description 📓 
Set up the DEV deployment for ARW. Requirements are highlighted in the [SDD](https://github.com/kartoza/kartoza-devops/blob/main/docs/sdd/app-0024/solution-design-app-0024.md).

### Assumptions ❓ 
None.

### Dependencies 🔗 
ARW SDD.

### Success Criteria 👍 
ARW is deployed to DEV and accessible to users.

**Comment by LokoMoloko98** [comment]
The Dev environment has been set up and deployed and accessible on https://arw.dev.do.kartoza.com/
