### ISSUE TITLE
DevOps: CI/CD pipelines

### ISSUE THREAD

**Issue by amyburness** [kartoza/africa_rangeland_watch#27]
### Description 📓 
Set up the CI/CD pipelines for ARW. SDLC requirements are highlighted in the [SDD](https://github.com/kartoza/kartoza-devops/blob/main/docs/sdd/app-0024/solution-design-app-0024.md).

### Assumptions ❓ 
None.

### Dependencies 🔗 
ARW SDD.
DEV environment.
STA environment.

### Success Criteria 👍 
ARW pipelines are in place to allow for automated builds and deploys to DEV and STA.

**Comment by LokoMoloko98** [comment]
The DEV environment Jenkins build is successfully deployed and builds the latest image

**Comment by LokoMoloko98** [comment]
The STA environment Jenkins build is successfully deployed and builds the latest pre-release:
https://jenkins.do.kartoza.com/job/kartoza/job/apps/job/arw_build_sta/

**Comment by LokoMoloko98** [comment]
The ARW Jenkins pipelines are in place and they automatically build the ARW images and deploy them to the DEV and STA environments respectfully.
