### ISSUE TITLE
UI/UX for ARW

### ISSUE THREAD

**Issue by amyburness** [kartoza/africa_rangeland_watch#3]
We need to make a wireframe for the UI/UX of the system based off the input from the client in the UR meetings. 

See the following document from the client that outlines the basic UI/UX 

[ARW_Design_Mock_up_Styles_Analysis.docx](https://github.com/user-attachments/files/17275267/ARW_Design_Mock_up_Styles_Analysis.docx)

**Comment by amyburness** [comment]
Tanks list for the UI Process: 

- [ ] Barebones UI
- [ ] Full workflow

**Comment by LenevJ** [comment]
Find the Figma file for ARW here:

[Africa Rangeland Watch_Wireframing Workflow ](https://www.figma.com/design/BlAYm1Z8wdEYA5faH8XT8L/Africa-Rangeland-Watch_Wireframing-Workflow?node-id=0-1&t=3Htlsb6YT8RsFgMe-1)

**Comment by amyburness** [comment]
@LenevJ  here is the rough dashboard builder logic
 
![Image](https://github.com/user-attachments/assets/5e64caaf-74fd-4080-aa5e-3466200dcde1)
 also here: https://drive.google.com/file/d/1XixuyVqs4uzUlMPi9ela1_lhg5_e4o8B/view?usp=sharing

**Comment by amyburness** [comment]
Layers: 
![image](https://github.com/user-attachments/assets/f6abdc31-afa0-402b-bd32-2fc5b0c0932e)

**Comment by amyburness** [comment]
Mapstore, Metabase etc. an off-the-Shelf option could be useful.
