### ISSUE TITLE
System design: System Architecture

### ISSUE THREAD

**Issue by amyburness** [kartoza/africa_rangeland_watch#4]
The system architecture for ARW will be based on the UR  document and the interactions with the client. We will need input from @lgkgh and @dimasciput to create a system architecture and data flow diagram.

Please generate the diagrams in the shared Draw.io file here: https://drive.google.com/file/d/1XixuyVqs4uzUlMPi9ela1_lhg5_e4o8B/view?usp=sharing

**Comment by amyburness** [comment]
@dimasciput Please can you make the formal system diagram based on the rough one below and make the SDD
![image](https://github.com/user-attachments/assets/3f449014-264e-430d-b030-4eb5bd7d926e)

**Comment by LokoMoloko98** [comment]
@dimasciput, here is the ARW SDD url: https://github.com/kartoza/kartoza-devops/blob/sdd-ARW/docs/sdd/app-0024/solution-design-template.md

**Comment by amyburness** [comment]
Specifications: 

- CPU (i5)
- RAM (16G)
- Storage (256G)
- CPU cores (14)

**Comment by LokoMoloko98** [comment]
When creating the SDD, the SANBI SDD will serve as inspiration

**Comment by LokoMoloko98** [comment]
The SDLC flow will be the same as Geohosting

**Comment by LokoMoloko98** [comment]
![solution-design-app-0024-Logical_Diagram drawio](https://github.com/user-attachments/assets/6f2f413e-57e0-463e-82fe-da62b86e6993)

**Comment by LokoMoloko98** [comment]
![Screenshot 2024-10-29 120714](https://github.com/user-attachments/assets/47c5a16a-3271-4544-9f96-c61f0bf507b1)

**Comment by amyburness** [comment]
Done to review please consult to SDD document.
