### ISSUE TITLE
Establish cloud infrastructure on Kartoza K8s platform, assuming on GCP.

### ISSUE THREAD

**Issue by amyburness** [kartoza/africa_rangeland_watch#6]
The output is the infrastructure framework on GCP

**Comment by LokoMoloko98** [comment]
The cloud Infrastructure will be deployed in the Digital ocean environment.
cc: @lgkgh, @zamuzakki, @dimasciput, @amyburness

**Comment by amyburness** [comment]
Staging and Dev exist for the project with the supporting infrastructure. The GCP task needs to be addressed in Phase 2. A new ticket will be created for this specific task.
