### ISSUE TITLE
Create Django Models, API Views, and Notification System for Support Staff

### ISSUE THREAD

**Issue by tinashechiraya** [kartoza/africa_rangeland_watch#84]
This task involves designing Django models for support tickets, creating API views to handle fetching and saving this data, and implementing an automated email notification system that uses email templates to notify support staff of updates.

- [x] Create Django Models:
- [x] Create API Views
- [x] create a Notification System:
a function to send email notifications to support staff when an event occurs (e.g., a new ticket).
a function to notify user when the ticket has been update

**Comment by dimasciput** [comment]
models : https://github.com/kartoza/africa_rangeland_watch/blob/main/django_project/alerts/models.py
