### ISSUE TITLE
When route is private and user not logged in yet, should show login modal

### ISSUE THREAD

**Issue by meomancer** [kartoza/africa_rangeland_watch#86]
# Problem
Map is private, and it is in navbar. When user click it without login, it will redirect to home again.

# Solution
Show sign in modal when clicking link that is Private Route

**Comment by tinashechiraya** [comment]
Okay I see what you mean .
For private routes instead of redirecting to home show login modal then after success login proceed to route.

I will add a patch for this . Thanks @meomancer
