### ISSUE TITLE
implement registration and forgot password

### ISSUE THREAD

**Issue by tinashechiraya** [kartoza/africa_rangeland_watch#91]
![Screenshot from 2024-11-18 08-30-33](https://github.com/user-attachments/assets/4c2b226d-c54e-478b-a765-cff9428fcb2c)
![Screenshot from 2024-11-18 08-30-54](https://github.com/user-attachments/assets/d59702da-23cc-446f-aa2e-64b1cec57b04)

Registration
user will provide their registration details and receive an email with a confirmation link
the link will redirect them to the website to complete registration

Forgot Password
user will provide their email and a reset link will be emailed to them
the link will return them to the site page where they can provide their new password

**Comment by amyburness** [comment]
@LenevJ is there a forgot password email template?
